runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: admin.handlers

- url: /.*
  script: main.handlers

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
